version: 2

sources:
  - name: raw_btc_source
    database: BTC_DATABASE
    schema: BTC_SCHEMA

    tables:
      - name: BTC_TRANSACTIONS
        freshness:
          warn_after:
            count: 24
            period: hour
        #          error_after:
        #            count: 24
        #            period: hour
        loaded_at_field: BLOCK_TIMESTAMP