-- Suspends Task
ALTER
TASK BTC_DATABASE.BTC_SCHEMA.BTC_LOAD_TASK SUSPEND;

-- Resumes Task
ALTER
TASK BTC_DATABASE.BTC_SCHEMA.BTC_LOAD_TASK RESUME;

-- Immediate execute Task
EXECUTE TASK BTC_DATABASE.BTC_SCHEMA.BTC_LOAD_TASK;
