
---------------------------
-- BTC_DATABASE.BTC_SCHEMA;
---------------------------
SELECT * FROM BTC_DATABASE.BTC_SCHEMA.BTC_TRANSACTIONS LIMIT 10;
SELECT * FROM BTC_DATABASE.BTC_SCHEMA.BTC_TRANSACTIONS WHERE HASH_KEY='d86aa794148835f4a051c81f94e2db7cbd1f7ab49dc575cfdb1893e2937f5523';
SELECT COUNT(*) FROM BTC_TRANSACTIONS;


---------------------------
-- BTC_DATABASE.DBT_SCHEMA
---------------------------
SELECT * FROM BTC_DATABASE.DBT_SCHEMA.STG2_TRANSACTION_PAYMENT_TABLE LIMIT 10;