---------------------------
-- BTC_DATABASE.BTC_SCHEMA;
---------------------------
SELECT * FROM BTC_DATABASE.DBT_SCHEMA.STG5_TRANSACTION_USD_ALERT_TABLE ORDER BY TOTAL_BITCOINS_USD DESC;
SELECT * FROM BTC_DATABASE.DBT_SCHEMA.STG5_TRANSACTION_USD_ALERT_TABLE ORDER BY TOTAL_BITCOIN_TRANSACTIONS DESC;


---------------------------
-- BTC_DATABASE.BTC_SCHEMA;
---------------------------
SELECT COUNT(*) FROM BTC_TRANSACTIONS;
SELECT * FROM BTC_DATABASE.BTC_SCHEMA.BTC_TRANSACTIONS LIMIT 10;
SELECT * FROM BTC_DATABASE.BTC_SCHEMA.BTC_TRANSACTIONS WHERE HASH_KEY='d86aa794148835f4a051c81f94e2db7cbd1f7ab49dc575cfdb1893e2937f5523';

---------------------------
-- BTC_DATABASE.DBT_SCHEMA
---------------------------
SELECT * FROM BTC_DATABASE.DBT_SCHEMA.STG2_TRANSACTION_PAYMENT_TABLE LIMIT 10;
SELECT * FROM BTC_DATABASE.DBT_SCHEMA.STG4_TRANSACTION_ALERT_TABLE LIMIT 10;
-- bc1qx2x5cqhymfcnjtg902ky6u5t5htmt7fvqztdsm028hkrvxcl4t2sjtpd9l
-- bc1q7cyrfmck2ffu2ud3rn5l5a8yv6f0chkp0zpemf
-- bc1qm34lsc65zpw79lxes69zkqmk6ee3ewf0j77s3h
SELECT * FROM BTC_DATABASE.DBT_SCHEMA.STG5_TRANSACTION_USD_ALERT_TABLE LIMIT 10;


---------------------------
-- SEEDS DATA
---------------------------
SELECT * FROM BTC_DATABASE.DBT_SCHEMA.BTC_USD_MAX LIMIT 5;
